---
title: "Comissão de Modelos"
author: "Forplad/ANDIFES"
date: "16 de dezembro de 2016"
output: html_document
---

# Introdução

A secretaria de Educação SUperior do MEC adota uma Matriz de Alocação de Recursos Orçamentários para fazer jus às despesas de custeio das Instituições Federais de Ensino Superior. Essa matriz traz em seu contexto a necessidade de diversos indicadores calculados sobre uma base de dados anuais de caráter acadêmico.

Em 1999 o MEC desemvolveu e implementou um movo modelo de alocação de recursos, adaptando o modelo de financiamento inglês (HEFCE), onde uma de suas características principais era o conceito de produtividade acadêmica.

Atendendo a críticas quan ao modelo que colocavam as IFES em conpetição excessiva por recursos, a SESu/MEV convidou a ANDIFES e o FORPLAD, em 2002, para pensarem conjuntamente uma proposta com as seguintes características:

1. Reconhecimento da heterogeneidade do Sistema IFES;
2. Parâmetros indutores para a diminuição da evasão e retenção;
3. Incentivo a criação de cursos noturnos;
4. Previsão de expansão do sistema;
5. Utilização de indicadores auditáveis e facilmente verificáveis;
6. Equalização de distorções no sistema.

O principal indicador do modelo é o ** aluno equivalente (NFTE) **, composto de quatro indicadores parciais, conforme os diferentes níveis educacionais (Graduação, Mestrado stricto sensu, Doutorado e Residência Médica).

Os dados são obtidos hoje a partir da coleta do Censo da Educação Superior e dos dados do COLETA CAPES.

## O Modelo Andifes

Existem algumas diferenças metodológicas para o cálculo do aluno equivalente (que devem ser observadas na leitura dos documentos nesse repositório, na pasta ANDIFES). Para cursos em regime de graduação em regime regular temos:

$$ {NFTe}^i_{(G)} = \left \{ \left[N_{Di} \times D  \times (1 + R) \right ] + \left [ \left( \frac{N_i - N_{Di}}{4} \times D \right) \right ] \right \} \times BT \times BFS  \times PG $$

Onde

Variável         | Significado
-----------------| -----------
$(NFTe)^i_{(G)}$ | Número de alunos equivalestes (graduação) para o i-ésimo curso
$N_{Di}$         | Número de Diplomados;
$D$              | Duração Padrão do Curso;
$R$              | Fator de Retenção;   
$N_{i}$          | Número de Ingressantes;
$BT$             | Bônus por turno Noturno (7%);
$BFS$            | Bônus por curso fora de sede (5%);
$PG$             | Peso do Grupo

Na expressão acima o Peso do Grupo, o Fator de Retenção e a Duração Padrão são variáveis de modelo, que buscam representar os diferentes custos de cada curso, ou seja, são as propriedades dos cursos individuais.

Os valores atuais são baseados em estudo do FORGRAD na década de 80 e nas variáveis do modelo inglês de 1997.

GRUPO | PG   | ÁREA | DESCRIÇÃO DA ÁREA                   |  R     |  D 
------|------|------|-------------------------------------|--------|-----|
A1    | 4,5  | CS1  | Medicina                            | 0,0650 | 6
A1    | 4,5  | CS2  | Veterinária, Odontologia, Zootecnia | 0,0650 | 5
A2    | 2,0  | CET  | Ciências Exatas e da Terra          | 0,1325 | 4
A2    | 2,0  | CB   | Ciências Biológicas                 | 0,1250 | 4
A2    | 2,0  | ENG  | Engenharias                         | 0,0820 | 5
A2    | 2,0  | TEC  | Tecnólogos                          | 0,0820 | 3
A2    | 2,0  | CS3  | Nutrição, Farmácia                  | 0,0660 | 5
A2    | 2,0  | CA   | Ciências Agrárias                   | 0,0500 | 5
A3    | 1,5  | CE2  | Ciências Exatas - Computação        | 0,1325 | 4
A3    | 1,5  | CE1  | Ciências Exatas - Matemática e Estatística  | 0,1325 | 4
A3    | 1,5  | CSC  | Arquitetura e Urbanismo        | 0,1200 | 4
A3    | 1,5  | A  | Artes        | 0,1150 | 4
A3    | 1,5  | M  | Música        | 0,1150 | 4
A3    | 1,5  | CS4  | Enfermagem, Fisiotrapia, Fonoaudiologia e Educação Física   | 0,0660 | 5
A4    | 1,0  | CSA  | Ciências Sociais Aplicadas        | 0,1200 | 4
A4    | 1,0  | CSB  | Direito        | 0,1200 | 5
A4    | 1,0  | LL  | Linguística e Letras        | 0,1150 | 4
A4    | 1,0  | CH  | Ciências Humanaas        | 0,1000 | 4
A4    | 1,0  | CH1  | Psicologia        | 0,1100 | 5
A4    | 1,0  | CH2  | Formação de Professor        | 0,1100 | 4


A Comissão de Modelos ForPLAD/ANDIFES vem trabalhando nesses descritores para que possam melhor descrever a realidade brasileira.

# Material de Referência

1. Arquivos ANDIFES
  + Matriz OCC 2016
  + Modelo Inglês 98
  + Relatório SESu coleta de dados 2006
2. Arquivos HEFCE
  + Informações sobre o modelo Inglês atual
  + Metodologia TRAC para análise de custos
  + White papers
3. Arquivos INEP
  + Censo 2010 - 2015 (Cursos e IES apenas)
  + Tabela OCDE 2009 de códigos de cursos
4. Arquivos MPOG
  + PLOA 2010 - 2016
  + APlicações diretas do Governo Federal 2010 - 2011
5. Arquivos DADOS_ABERTOS

# R Scripts 

# TO-DO

# Responsabilidade

Esse projeto é mantido por Luciano Barosi de Lemos